services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./mariadb:/config
    # Se eliminan los ports públicos (3306:3306) por seguridad; la comunicación es interna
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URI=https://${DOMINIO}:${PUERTO}/phpmyadmin/
    # Se elimina ports (8080:80) ya que SWAG resolverá la ruta /phpmyadmin/ internamente
    depends_on:
      - mariadb

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - URL=${DOMINIO}
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - SUBDOMAINS=
    volumes:
      - ./swag:/config
    ports:
      - ${PUERTO}:443/tcp
      - 80:80
    restart: unless-stopped

  crud:
    image: crud
    build:
      context: ./crud
    container_name: crud
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DB=rectitrack_db
      - MYSQL_HOST=mariadb
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mariadb